### ISSUE TITLE
3.0.0: Videos are played in separate window

### ISSUE THREAD

**Issue by bobby285271** [elementary/videos#356]
### What Happened?

<img src="https://github.com/elementary/videos/assets/20080233/d9fc5bb4-ffa5-4b9b-ae04-783c76de87e6" width=50%>

Not sure if this is expected, in 3.0.0 the videos are now played in separate window titled `io.elementary.videos`, while the control buttons (pulse, playlist, settings, ...) in another window named `Library`

### Steps to Reproduce

1. Build 3.0.0
2. Open a mp4 file, [link to the mp4 file I used](https://github.com/elementary/videos/assets/20080233/56011f3f-53e7-4a47-bda3-58bf45c64a1a)

<img src="https://github.com/elementary/videos/assets/20080233/3b3ac841-af53-4a25-97d1-8e1a8373a82f" width=25%>

### Expected Behavior

Video and {pulse, playlist, settings} button in the same window. 2.9.1 looks fine

### OS Version

NixOS unstable

### Software Version

Latest release (I have run all updates)

**Comment by bobby285271** [comment]
Oh sorry this is a packaging issue, looking at https://github.com/elementary/videos/blob/3.0.0/src/Services/PlaybackManager.vala#L40 starting from 3.0.0 this needs a gst-plugins-good with gtk support. Should be introduced in https://github.com/elementary/videos/commit/218f760f878a26cd8523c3faf37e99a549068026.

Backtrace with `G_DEBUG=fatal-criticals` for reference

<details>

```
(gdb) bt
#0  0x00007ffff7db3241 in g_logv () from /nix/store/5gs8a87g7dfy1pgylzc7bgri68fd8a66-glib-2.76.4/lib/libglib-2.0.so.0
#1  0x00007ffff7db34cf in g_log () from /nix/store/5gs8a87g7dfy1pgylzc7bgri68fd8a66-glib-2.76.4/lib/libglib-2.0.so.0
#2  0x00007ffff7eb55e9 in g_object_get () from /nix/store/5gs8a87g7dfy1pgylzc7bgri68fd8a66-glib-2.76.4/lib/libgobject-2.0.so.0
#3  0x000000000041d3ba in audience_playback_manager_constructor (type=<optimized out>, n_construct_properties=<optimized out>, 
    construct_properties=<optimized out>) at ../src/Services/PlaybackManager.vala:40
#4  0x00007ffff7eb1caf in g_object_new_with_custom_constructor ()
   from /nix/store/5gs8a87g7dfy1pgylzc7bgri68fd8a66-glib-2.76.4/lib/libgobject-2.0.so.0
#5  0x00007ffff7eb381c in g_object_new_with_properties ()
   from /nix/store/5gs8a87g7dfy1pgylzc7bgri68fd8a66-glib-2.76.4/lib/libgobject-2.0.so.0
#6  0x00007ffff7eb4421 in g_object_new () from /nix/store/5gs8a87g7dfy1pgylzc7bgri68fd8a66-glib-2.76.4/lib/libgobject-2.0.so.0
#7  0x000000000041d248 in audience_playback_manager_construct (object_type=<optimized out>) at ../src/Services/PlaybackManager.vala:6
#8  0x000000000041e0d0 in audience_playback_manager_new () at ../src/Services/PlaybackManager.vala:6
#9  0x000000000041e0de in __lambda15_ () at ../src/Services/PlaybackManager.vala:34
#10 0x000000000041e0ec in ___lambda15__gthread_func (self=<optimized out>) at /build/source/build/PlaybackManager.c:307
#11 0x00007ffff7dd78bd in g_once_impl () from /nix/store/5gs8a87g7dfy1pgylzc7bgri68fd8a66-glib-2.76.4/lib/libglib-2.0.so.0
#12 0x000000000041c4e1 in audience_playback_manager_get_default () at ../src/Services/PlaybackManager.vala:34
#13 0x00000000004279b8 in audience_player_page_constructor (type=<optimized out>, n_construct_properties=<optimized out>, 
    construct_properties=<optimized out>) at ../src/Widgets/Player/PlayerPage.vala:57
#14 0x00007ffff7eb1e7b in g_object_new_with_custom_constructor ()
   from /nix/store/5gs8a87g7dfy1pgylzc7bgri68fd8a66-glib-2.76.4/lib/libgobject-2.0.so.0
#15 0x00007ffff7eb381c in g_object_new_with_properties ()
   from /nix/store/5gs8a87g7dfy1pgylzc7bgri68fd8a66-glib-2.76.4/lib/libgobject-2.0.so.0
#16 0x00007ffff7eb4421 in g_object_new () from /nix/store/5gs8a87g7dfy1pgylzc7bgri68fd8a66-glib-2.76.4/lib/libgobject-2.0.so.0
#17 0x0000000000427ebd in audience_player_page_construct (object_type=<optimized out>) at ../src/Widgets/Player/PlayerPage.vala:28
#18 0x00000000004282c6 in audience_player_page_new () at ../src/Widgets/Player/PlayerPage.vala:28
#19 0x0000000000411107 in audience_window_constructor (type=<optimized out>, n_construct_properties=<optimized out>, 
    construct_properties=<optimized out>) at ../src/Window.vala:113
#20 0x00007ffff7eb1caf in g_object_new_with_custom_constructor ()
   from /nix/store/5gs8a87g7dfy1pgylzc7bgri68fd8a66-glib-2.76.4/lib/libgobject-2.0.so.0
#21 0x00007ffff7eb381c in g_object_new_with_properties ()
   from /nix/store/5gs8a87g7dfy1pgylzc7bgri68fd8a66-glib-2.76.4/lib/libgobject-2.0.so.0
#22 0x00007ffff7eb4421 in g_object_new () from /nix/store/5gs8a87g7dfy1pgylzc7bgri68fd8a66-glib-2.76.4/lib/libgobject-2.0.so.0
#23 0x000000000041391b in audience_window_construct (object_type=<optimized out>) at ../src/Window.vala:23
#24 0x000000000041397d in audience_window_new () at ../src/Window.vala:23
#25 0x000000000040ebdd in audience_app_real_activate (base=0x6d4880) at ../src/Application.vala:103
--Type <RET> for more, q to quit, c to continue without paging--
#26 0x00007ffff7eac6c9 in _g_closure_invoke_va () from /nix/store/5gs8a87g7dfy1pgylzc7bgri68fd8a66-glib-2.76.4/lib/libgobject-2.0.so.0
#27 0x00007ffff7ec62e7 in g_signal_emit_valist () from /nix/store/5gs8a87g7dfy1pgylzc7bgri68fd8a66-glib-2.76.4/lib/libgobject-2.0.so.0
#28 0x00007ffff7ec659f in g_signal_emit () from /nix/store/5gs8a87g7dfy1pgylzc7bgri68fd8a66-glib-2.76.4/lib/libgobject-2.0.so.0
#29 0x00007ffff70b2348 in g_application_real_local_command_line ()
   from /nix/store/5gs8a87g7dfy1pgylzc7bgri68fd8a66-glib-2.76.4/lib/libgio-2.0.so.0
#30 0x00007ffff70b24d6 in g_application_run () from /nix/store/5gs8a87g7dfy1pgylzc7bgri68fd8a66-glib-2.76.4/lib/libgio-2.0.so.0
#31 0x000000000040ee27 in _vala_main (args=<optimized out>, args_length1=<optimized out>) at ../src/Application.vala:152
#32 0x000000000040ee4a in main (argc=<optimized out>, argv=<optimized out>) at ../src/Application.vala:147
```

</details>

The critical message 

```
GLib-GObject-CRITICAL **: 20:07:28.253: g_object_get: assertion 'G_IS_OBJECT (object)' failed
```

**Comment by bobby285271** [comment]
In case anyone is hitting this again when packaging 8.0.0 (like me...), gst-plugins-rs is now needed for the GTK4 sink according to https://github.com/elementary/videos/pull/333 :joy:
