### ISSUE TITLE
Crash when resuming MP4 video

### ISSUE THREAD

**Issue by jeremypw** [elementary/videos#84]
[Juno, master] A crash consistently occurs when resuming an MP4 video (other formats not tested yet).  
* Start an MP4 video
* Press the `Back` button
* Chooser resume option from the welcome page.

Running in terminal with --debug flag gives following output.

```
libGL error: failed to create drawable
libGL error: failed to create drawable

(io.elementary.videos:26293): Gdk-ERROR **: 11:12:20.415: The program 'io.elementary.videos' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadContext'.
  (Details: serial 35092 error_code 170 request_code 155 (GLX) minor_code 26)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/breakpoint trap (core dumped)
```

Backtrace from gdb with GDK_SYNCHRONIZE set was:

```
Thread 1 (Thread 0x7ffff7fb2680 (LWP 26921)):
#0  0x00007ffff6175c41 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff6178571 in g_log_writer_default () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff61767de in g_log_structured_array () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff617722e in g_log_structured_standard () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff721dc31 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#5  0x00007ffff722aab3 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#6  0x00007ffff6c9fc8d in _XError () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#7  0x00007fffe4f9a3e4 in  () at /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0
#8  0x00007fffe4f9a2c9 in  () at /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0
#9  0x00007fffe51f41dd in  () at /usr/lib/x86_64-linux-gnu/libGLX.so.0
#10 0x00007fffe51f5f82 in  () at /usr/lib/x86_64-linux-gnu/libGLX.so.0
---Type <return> to continue, or q <return> to quit---
#11 0x00007fffac07b6f0 in  () at /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstvaapi.so
#12 0x00007fffac030652 in  () at /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstvaapi.so
#13 0x00007fffac03049e in  () at /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstvaapi.so
#14 0x00007fffac010e50 in  () at /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstvaapi.so
#15 0x00007ffff66ca7fe in  () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#16 0x00007ffff66cfc02 in  () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#17 0x00007ffff66cf650 in  () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#18 0x00007ffff66d15e8 in gst_buffer_pool_release_buffer () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#19 0x00007ffff66ca933 in  () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#20 0x00007ffff66ff88c in gst_mini_object_unref () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#21 0x00007ffff467ebc8 in _cogl_object_default_unref () at /usr/lib/x86_64-linux-gnu/libcogl.so.20
#22 0x00007ffff4694564 in  () at /usr/lib/x86_64-linux-gnu/libcogl.so.20
#23 0x00007ffff616c45d in g_list_foreach () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007ffff4690f47 in  () at /usr/lib/x86_64-linux-gnu/libcogl.so.20
#25 0x00007ffff4690888 in  () at /usr/lib/x86_64-linux-gnu/libcogl.so.20
#26 0x00007ffff4690de8 in  () at /usr/lib/x86_64-linux-gnu/libcogl.so.20
#27 0x00007ffff7bba087 in  () at /usr/lib/x86_64-linux-gnu/libclutter-gst-3.0.so.0
#28 0x00007ffff644801b in g_boxed_free () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#29 0x00007ffff7bc48b4 in  () at /usr/lib/x86_64-linux-gnu/libclutter-gst-3.0.so.0
#30 0x00007ffff6449f6d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#31 0x00007ffff645cd3e in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#32 0x00007ffff64653f5 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#33 0x00007ffff6465e0f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#34 0x00007ffff7bc7695 in  () at /usr/lib/x86_64-linux-gnu/libclutter-gst-3.0.so.0
#35 0x00007ffff6170287 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#36 0x00007ffff61704c0 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#37 0x00007ffff617054c in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#38 0x00007ffff7555d2d in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#39 0x00007ffff5378659 in granite_application_run (self=0x555555d8c130, args=0x7fffffffde08, args_length1=1)
    at /media/jeremy/Shared/shared_data/Vala/Elementary/granite-branches/granite/build/lib/Application.c:276
#40 0x000055555556232c in _vala_main (args=0x7fffffffde08, args_length1=1)
    at /media/jeremy/Shared/shared_data/Vala/Elementary/videos-audience-branches/videos/src/Audience.vala:107
#41 0x000055555556236a in main (argc=1, argv=0x7fffffffde08) at /media/jeremy/Shared/shared_data/Vala/Elementary/videos-audience-branches/videos/src/Audience.vala:95
```

t a a bt indicated there were 58 other threads running (!)

**Comment by jeremypw** [comment]
This also occurs when, instead of resuming, the same (or different) MP4 video is loaded using the FileChooser.

**Comment by jeremypw** [comment]
Crash does not occur with WMV and AVI formats.

Crash also occurs with MOV format.

**Comment by ryonakano** [comment]
Although I don't confirm the fact, this issue might not occur on daily, as #95 does not.

**Comment by jeremypw** [comment]
This seems to be fixed in the current master
