### ISSUE TITLE
Crash when replaying MP4 video in your library

### ISSUE THREAD

**Issue by ryonakano** [elementary/videos#95]
This may be related #84.

A crash occurs when replaying MP4 video in your library.
On Juno Beta, with Videos 2.6.1

## Steps to reproduce the behavior

* Prepare a MP4 video in ~/Videos
* Open the app, click "Browse Library" and select the video that you prepared
* The video begins. Then back to library by clicking the "Library" button
* Again, select the video you prepared
* The app crashes

The log when crashed:

```
libGL error: failed to create drawable
libGL error: failed to create drawable

(io.elementary.videos:7235): Gdk-ERROR **: 11:09:37.644: The program 'io.elementary.videos' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadContext'.
  (Details: serial 16619 error_code 170 request_code 155 (GLX) minor_code 26)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/breakpoint trap
```

**Comment by arshubham** [comment]
@ryonakano I am unable to reproduce this issue on master. Are you still experiencing this?

**Comment by ryonakano** [comment]
Hmm, I tested on master on the latest Juno but I'm still facing the issue unfortunately.

Here is my system information:

![Screenshot from 2019-10-11 07-26-37](https://user-images.githubusercontent.com/26003928/66611107-7e022f80-ebf8-11e9-9497-cc90ba777d0e.png)

And the screencast of the issue (it is not played smoothly because of the low frame late to keep the file size uploadable to GitHub):

![Peek 2019-10-11 07-19](https://user-images.githubusercontent.com/26003928/66610813-afc6c680-ebf7-11e9-8692-513fbaf9aff4.gif)

And GDB log:

```
#0  0x00007ffff6172ea1 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff6175839 in g_log_writer_default () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff6173a8e in g_log_structured_array () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff61744ee in g_log_structured_standard () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff721cc41 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#5  0x00007ffff7229ac3 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#6  0x00007ffff6ca08fa in _XError () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#7  0x00007fffe5005be4 in  () at /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0
#8  0x00007fffe5005ac9 in  () at /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0
#9  0x00007fffe52491dd in  () at /usr/lib/x86_64-linux-gnu/libGLX.so.0
#10 0x00007fffe524af82 in  () at /usr/lib/x86_64-linux-gnu/libGLX.so.0
#11 0x00007fffc456bc10 in  () at /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstvaapi.so
#12 0x00007fffc4520b62 in  () at /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstvaapi.so
#13 0x00007fffc45209ae in  () at /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstvaapi.so
#14 0x00007fffc45010a0 in  () at /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstvaapi.so
#15 0x00007ffff66c88be in  () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#16 0x00007ffff66cdcd2 in  () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#17 0x00007ffff66cd720 in  () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#18 0x00007ffff66cf6b8 in gst_buffer_pool_release_buffer () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#19 0x00007ffff66c89f3 in  () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#20 0x00007ffff66fda1c in gst_mini_object_unref () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#21 0x00007ffff46aac68 in _cogl_object_default_unref () at /usr/lib/x86_64-linux-gnu/libcogl.so.20
#22 0x00007ffff46c0634 in  () at /usr/lib/x86_64-linux-gnu/libcogl.so.20
#23 0x00007ffff61695ed in g_list_foreach () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007ffff46bd017 in  () at /usr/lib/x86_64-linux-gnu/libcogl.so.20
#25 0x00007ffff46bc958 in  () at /usr/lib/x86_64-linux-gnu/libcogl.so.20
#26 0x00007ffff46bceb8 in  () at /usr/lib/x86_64-linux-gnu/libcogl.so.20
#27 0x00007ffff7bba087 in  () at /usr/lib/x86_64-linux-gnu/libclutter-gst-3.0.so.0
#28 0x00007ffff64461bb in g_boxed_free () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#29 0x00007ffff7bc48b4 in  () at /usr/lib/x86_64-linux-gnu/libclutter-gst-3.0.so.0
#30 0x00007ffff644810d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#31 0x00007ffff645b05e in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#32 0x00007ffff6463715 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#33 0x00007ffff646412f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#34 0x00007ffff7bc7695 in  () at /usr/lib/x86_64-linux-gnu/libclutter-gst-3.0.so.0
#35 0x00007ffff616d417 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#36 0x00007ffff616d650 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#37 0x00007ffff616d6dc in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#38 0x00007ffff7554e3d in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#39 0x000055555556223b in _vala_main (args=0x7fffffffdcb8, args_length1=1) at ../src/Application.vala:97
#40 0x0000555555562279 in main (argc=1, argv=0x7fffffffdcb8) at ../src/Application.vala:85
```

@arshubham Are you on daily or Juno?

**Comment by arshubham** [comment]
Yes I am on daily. Can you share the video file? I tested it with some samples was working fine for me.

**Comment by ryonakano** [comment]
I see. I've uploaded the file [here](https://drive.google.com/file/d/1TPLNNVneUfTlogi9EW2aAMLO_eVdl0wl/view?usp=sharing) (which was originally downloaded from https://youtu.be/SkVqJ1SGeL0)

**Comment by arshubham** [comment]
@ryonakano I am still unable to reproduce it. https://youtu.be/2-4ZbOh2acQ
I have a all AMD system though. The GDB log suggests a crash is streamer. If you can, try it on the newer versions of gstreamer on eaon.

**Comment by ryonakano** [comment]
OK, I'll try installing daily and check if the issue resolved.

**Comment by ryonakano** [comment]
@arshubham I'm sorry for the delay, I have had trouble in installing daily onto my laptop for some reason. Finally, I installed it in VM and confirmed that the issue is not reproducable. Thank you for your investigation.
